name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to build and publish your .NET project
      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./publish_output

      # Step to create a release zip file
      - name: Create Release Zip
        run: |
          cd publish_output
          zip -r ../release.zip *
        working-directory: ./publish_output

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ needs.build.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
