name: Release Game

on:
  push:
    branches: [ master ]  # Change 'main' to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest  # Adjust OS if needed

    steps:
      - uses: actions/checkout@v3  # Checkout your code

      - name: Create Release Tag
        run: |
          git tag v0.0.1  # Replace with your desired tag name

      - name: Zip Release Folder
        run: |
          cd bin/Release/net8.0  # Change directory to your release folder
          zip -j hunters_era.zip .  # Create zip named "hunters_era.zip"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v0.0.1 # Use commit SHA as tag
          release_name: Hunters Era Release 0.0.1
          draft: false  # Set to true for draft releases
          prerelease: false  # Set to true for pre-releases
          file: bin/Release/net8.0/hunters_era.zip  # Path to your zip

